text = """
Neto de Cosme de Médici (o Velho), era filho de Pedro de Cosme de Médici e de Lucrécia Tornabuoni.[5] Casou-se em 4 de junho de 1469 com Clarice Orsini, chamada Leo. Era filha de Giacomo Orsini di Monterotondo. Teve sete filhos, dos quais João de Lourenço de Médici (futuro Papa Leão X).[6] Com a morte de seu pai, em 1469, Lourenço e seu irmão Juliano foram designados "príncipes do Estado" (em italiano principi dello Stato).

O futuro parecia tranquilo até que em 1478 aconteceu a Conspiração dos Pazzi, assim chamada em alusão à família envolvida no movimento, na verdade instigado pelos Salviati, banqueiros do Papa Sisto IV, inimigo dos Médicis.[7] Foi feito um plano para matar os dois irmãos Médici no Duomo de Florença, durante a missa, em 26 de abril, um domingo de Páscoa. Juliano morreu, Lourenço escapou, embora ferido, salvo pelo poeta Poliziano, que o trancou na sacristia.[1][8]

Os autores do plano, entre eles Francesco Salviati, arcebispo de Pisa, foram linchados pelo povo enfurecido. O Papa Sixto IV, cujo sobrinho Girolamo Riario era cúmplice, interditou a cidade de Florença por causa dos assassinatos de Salviati e dos Pazzi, apoiado pelo rei de Nápoles, Fernando I, conhecido como Don Ferrante.[7]

Sem ajuda de seus tradicionais aliados de Bolonha e Milão, Lourenço partiu sozinho para Nápoles, em 1480, colocando-se nas mãos de Don Ferrante. Este manteve Lourenço cativo durante três meses, antes de libertá-lo com muitos presentes. Graças a sua coragem e talento diplomático, Lourenço convenceu Don Ferrante de que o Papa poderia também voltar-se contra ele, caso obtivesse muito sucesso no norte. Assim, firma-se a paz ainda em 1480. Com isso, Lourenço forçava o papa a também aceitar a paz. Segundo Maquiavel, Lourenço expôs a própria vida para restaurar a paz, indo pessoalmente negociar condições favoráveis. E mesmo depois de seu êxito, recusou tudo, desejou ser apenas o mais ilustre dos cidadãos de Florença. Com exceção de Siena, toda a Toscana passara a aceitar o governo de Florença, que oferecia o espetáculo de um extenso principado, governado por uma república de cidadãos livres e iguais.

Em geral, Lourenço manteve a política de seu avô, embora tenha sido menos prudente e mais disposto à tirania. Dotado de grande inteligência, governou num clima de prosperidade pública, aumentando a influência de sua família por toda a Itália, e manteve as instituições republicanas em Florença, ainda que só na aparência: na verdade, Lourenço foi virtualmente um tirano. Utilizava-se de espiões, interferia na vida privada dos cidadãos mas conseguiu levar o comércio e a indústria de Florença a um nível superior ao de qualquer outra cidade da Europa.

Disseram dele: [quem?]

'Dirigiu sua hábil diplomacia de modo a obter paz na península, mantendo os cinco Estados principais unidos diante da ameaça crescente de uma invasão vinda dos Alpes. Florença não poderia ter um tirano melhor ou mais agradável, e o mundo jamais viu outro patrono de artistas e letrados como ele.'

Protetor de escritores, sábios e artistas, foi o impulsor das primeiras imprensas italianas. Lorenzo iniciou o movimento renascentista, que rejeita a ciência escolástica e teológica, para valorizar a pesquisa e a busca do sentido da vida, colocando o homem no centro do Universo. Seu palácio tornou-se o centro de uma cultura que, partindo da redescoberta da Antiguidade grega e latina na Europa (uma vez que os impérios islâmicos haviam sido, até então, guardiões e desenvolvedores desta sabedoria), levou a um extraordinário florescimento das artes e das letras naquela parte da Europa. Os maiores artistas e literatos frequentavam a sua corte, mas o que distinguia Lourenço de outros mecenas da época era a sua ativa participação intelectual nas atividades que promovia. Foi um elegante escritor em prosa e um poeta original. Os filósofos Marsílio Ficino e Pico della Mirandola, os poetas Pulci e Poliziano e grandes artistas como Botticelli e Ghirlandaio, eram seus hóspedes habituais. Michelangelo iniciou os seus estudos num ateliê patrocinado por Lourenço.

A paz de Lodi (1454), que havia colocado um fim às disputas entre Veneza e Milão, havia trazido o equilíbrio entre os estados italianos. Em grande parte, tal equilíbrio foi mantido graças às habilidades diplomáticas de Lourenço, considerado "o fiel da balança". De fato, procurava proteger o eixo formado por Florença, Milão e Nápoles das ambições venezianas e da ambiguidade papal. O clima de relativa paz também favoreceu o Renascimento.

Organizador de festas suntuosas, seus gastos excessivos puseram em perigo a fortuna dos Médici e despertaram a ira de Jerônimo Savonarola. Ao final da vida, Lourenço entrou em conflito com Savonarola, mas a lenda que este lhe recusou absolvição antes de morrer a menos que restaurasse a liberdade da cidade de Florença não é confirmada pelos historiadores.

Após sua morte, seu filho e sucessor Pedro II (Piero) (1471-1503) é expulso de Florença por uma revolta instigada por Savonarola, em 1494. O equilíbrio político é rompido e as rivalidades entre os estados italianos acabaram por dar espaço ao envolvimento de potências estrangeiras nas disputas.
"""
